# Practice 

September 21st, 2026

## Announcements

- About class projects

## In-class activity

- Gather in teams of maximum 5 people. 


You are consultant statisticians. A researcher has come to you to request help analyzing data generated by a designed experiment. They described the experiment in the following email: 

>I hope you are doing well. I am writing to request assistance with my statistical analysis for an aquaculture clinical field trial in the Bay of Fundy, Canada. Please find a description of the study below.  
>
>The data were generated from an experiment that was studying the effect of different feed additives in swine production. A total of 300 pigs were used in this study, with dietary treatment applied to pen in a randomized complete block design.
>
>- Feed additives were applied at the pen level.
>- Observations: 3 pigs per pen were sampled on day 5, 10, and 17 and fecal sample was then placed in drying oven at 55 C for 48 hours to determine fecal dry matter.
>
>I need help with the following:  
>
>- Describing the experiment design for materials and methods. 
>- Analyzing the data and determining: 
  - If there are differences between feed additives on fecal DM, 
  - If there is a "better feed additive" (assume more DM is better). 

- Download the [Rmd](../scripts/09212026_inclass_ex.Rmd) that will give you access to the data. 

**FINISH BY 12:20PM \& class debate**

1. Read the data, analyze it, and answer the researcher's questions. 
2. Mention one way they could improve the power of their experiment to detect differences in final weight between treatments. 

You may ask the researcher for missing information or for clarifications, if you think there's information missing (ask Josefina). 






